### ISSUE TITLE
add Linux build

### ISSUE THREAD

**Issue by schwebke** [ola-ct/impac-t#22]
add scripts and build files for a Linux build.

**Comment by 607011** [comment]
It's not that easy ;-) You'll also have to port the code parts marked with `#if defined(WIN32)`.

**Comment by 607011** [comment]
Is someone willing to port these parts and write a nice Makefile?

**Comment by 607011** [comment]
@schwebke provided a nice patch with basic Linux support #23

**Comment by aggsol** [comment]
Is CMake an option for a build system?

**Comment by 607011** [comment]
@aggsol Currently Linux builds are based on `make`. But do as you like to. TIA

**Comment by 607011** [comment]
Implemented via commit 37f2950b1419b0e82f3e8ce5929c99e7e4d37d86. Thank you, @schwebke !
