### ISSUE TITLE
git clone polluted with lot of binaries

### ISSUE THREAD

**Issue by andreygursky** [ola-ct/impac-t#24]
Hi,

I'd prefer not to have in a git repository 3rdparty libs, especially binaries:
- deploy/vcredist_x86.exe
- ffmpeg

At least, there should be a folder 3rdparty, where all this stuff belongs to (just like in e.g. opencv).

Thanks,
Andrey

**Comment by 607011** [comment]
Sorry. Maybe ffmpeg.exe, ffplay.exe and ffprobe.exe will be deleted in some revision. I provided the binaries for my and possibly other developers' and c't magazin readers' convenience.
