### ISSUE TITLE
Kompilieren unter Linux

### ISSUE THREAD

**Issue by daald** [ola-ct/impac-t#33]
Beim Befolgen der Instruktionen auf der Seite https://github.com/ola-ct/impac-t/wiki/Kompilieren-unter-Linux sind mir ein paar Fehler aufgefallen. Letztlich konnte ich das Spiel mit folgendem Script zum Laufen bringen:

```
xubuntu@xubuntu:~$ cat buildandrun.sh 
#!/bin/sh

set -x -e

sudo apt-get -y update
sudo apt-get -y install g++
sudo apt-get -y install zlib1g-dev libsfml-dev libbox2d-dev libglew-dev libgtk-3-dev
sudo apt-get -y install libboost-signals-dev libboost-regex-dev libboost-serialization-dev
sudo apt-get -y install libboost-system-dev libboost-filesystem-dev

sudo apt-get -y install git
sudo apt-get -y install git-gui
git clone https://github.com/ola-ct/impac-t.git
cd impac-t/Impact
make

mkdir ~/.impact/
ln -s $(readlink -f resources/*/) ~/.impact/

./impact
```

Unterschiede zum Original:
- sudo apt-get install libboost-system-dev libboost-filesystem-dev
- Die Symlinks, die kurz vor dem Start erstellt werden

**Comment by 607011** [comment]
Resolved. Thanks.
